version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'nicholemattera'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
